sudo: required
services:
  - docker

before_install:
  - docker build -t akintola/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akintola/multi-docker-test npm run test

after_success:
  - docker build -t akintola/multi-client ./client
  - docker build -t akintola/multi-server ./server
  - docker build -t akintola/multi-worker ./worker
  - docker build -t akintola/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password=stdin
  - docker push  akintola/multi-client
  - docker push  akintola/multi-server
  - docker push  akintola/multi-worker
  - docker push  akintola/multi-nginx