version: '3'
services:
  nginx:
    image: "akintola/multi-nginx"  
    ports:
      - "5000:80"
    depends_on:
      - api
      - client
  postgresql:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  client:
    image: "akintola/multi-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "akintola/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgresql
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "akintola/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379